import type { Metadata } from "next";
import "./assets/style/Global.scss";
import { gagalin, dreamingOutloud } from "./fonts";

export const metadata: Metadata = {
  title: "Le Club des Familles",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className={`${gagalin.variable} ${dreamingOutloud.variable}`}
    >
      <body className="antialiased">{children}</body>
    </html>
  );
}
